name: Deploy to Deno Deploy

on:
  push:
    branches: [master, development]

jobs:
  production:
    if: github.ref_name == 'master'
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Create .env
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: "DOTENV_"
        env:
          DOTENV_APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          DOTENV_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          DOTENV_TOKEN: ${{ secrets.TOKEN }}
          DOTENV_GUILD_ID: ${{ secrets.GUILD_ID }}
          DOTENV_THREADS_CATEGORY: ${{ secrets.THREADS_CATEGORY }}

      - uses: denoland/deployctl@v1
        with:
          project: readthebooks-bot
          entrypoint: main.ts

  preview:
    if: github.ref_name == 'development'
    environment: Preview
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Create .env
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: "DOTENV_"
        env:
          DOTENV_APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          DOTENV_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          DOTENV_TOKEN: ${{ secrets.TOKEN }}
          DOTENV_GUILD_ID: ${{ secrets.GUILD_ID }}
          DOTENV_THREADS_CATEGORY: ${{ secrets.THREADS_CATEGORY }}

      - uses: denoland/deployctl@v1
        with:
          project: readthebooks-bot-test
          entrypoint: main.ts
