name: Deploy to Deno Deploy

on:
  push:
    branches: [master, release]

jobs:
  deploy:
    needs: [environment]
    environment: ${{ needs.environment.outputs.name }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Create .env
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: "DOTENV_"
        env:
          DOTENV_APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          DOTENV_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          DOTENV_TOKEN: ${{ secrets.TOKEN }}
          DOTENV_GUILD_ID: ${{ secrets.GUILD_ID }}
          DOTENV_THREADS_CATEGORY: ${{ secrets.THREADS_CATEGORY }}

      - uses: denoland/deployctl@v1
        with:
          project: readthebooks-bot${{ needs.environment.outputs.name != 'Production' && '-test' }}
          entrypoint: main.ts

  environment:
    uses: ./.github/workflows/environment.yml
