name: Maintain threads

on:
  workflow_dispatch:
  schedule:
    - cron: "* */12 * * *"  # Every 12h

jobs:
  maintain_threads:
    strategy:
      matrix:
        environments: [Production, Preview]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environments }}
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.x

      - run: deno run --allow-env --allow-net --allow-read=. maintain-threads.ts
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          THREADS_CATEGORY: ${{ secrets.THREADS_CATEGORY }}
