name: Maintain threads

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # Every 12h

jobs:
  maintain_threads:
    strategy:
      matrix:
        environment: [Production, Preview]
      max-parallel: 1
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.x

      - name: Create .env
        uses: iamsauravsharma/create-dotenv@v1.2.1
        with:
          env-prefix: "DOTENV_"
        env:
          DOTENV_APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          DOTENV_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          DOTENV_TOKEN: ${{ secrets.TOKEN }}
          DOTENV_GUILD_ID: ${{ secrets.GUILD_ID }}
          DOTENV_THREADS_CATEGORY: ${{ secrets.THREADS_CATEGORY }}

      - name: Run maintain-threads.ts
        run: deno run --allow-env --allow-net --allow-read=. maintain-threads.ts
