name: Register commands

on:
  push:
    branches: [master, release]
    paths:
      - register-commands.ts
      - .github/workflows/register-commands.yml

jobs:
  register-commmands:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.x

      - run: deno run --allow-env --allow-net register-commands.ts
        env:
          TOKEN: ${{ secrets.TOKEN }}
