name: Register commands

on:
  push:
    branches: [master, development]
    paths:
      - commands.json
      - register-commands.ts
      - .github/workflows/register-commands.yml

jobs:
  production:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    environment: Production
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.x

      - run: deno run --allow-env --allow-net --allow-read=. register-commands.ts
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          TOKEN: ${{ secrets.TOKEN }}

  preview:
    runs-on: ubuntu-latest
    if: github.ref_name == 'development'
    environment: Preview
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.19.x

      - run: deno run --allow-env --allow-net --allow-read=. register-commands.ts
        env:
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          TOKEN: ${{ secrets.TOKEN }}
